-- Tablo kurulumları
CREATE TABLE AUTHORS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE PUBLISHERS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

CREATE TABLE BOOKS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    author_id NUMBER,
    publisher_id NUMBER,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES AUTHORS(id),
    CONSTRAINT fk_publisher FOREIGN KEY (publisher_id) REFERENCES PUBLISHERS(id)
);

CREATE TABLE AUDIT_LOGS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id NUMBER,
    action_time TIMESTAMP,
    db_user VARCHAR2(50)
);

-- Kitap loglama tetikleyicisi
CREATE OR REPLACE TRIGGER books_audit_trg
AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOGS (book_id, action_time, db_user)
    VALUES (:NEW.id, SYSTIMESTAMP, USER);
END;
/

-- Kitap operasyonları paket tanımı
CREATE OR REPLACE PACKAGE BOOK_OPERATIONS AS
    PROCEDURE add_book(p_title IN VARCHAR2, p_author_name IN VARCHAR2, p_publisher_name IN VARCHAR2);
END BOOK_OPERATIONS;
/

-- Kitap operasyonları paket gövdesi
CREATE OR REPLACE PACKAGE BODY BOOK_OPERATIONS AS
    PROCEDURE add_book(p_title IN VARCHAR2, p_author_name IN VARCHAR2, p_publisher_name IN VARCHAR2) IS
        v_author_id NUMBER;
        v_publisher_id NUMBER;
    BEGIN
        -- Yazar kontrolü (Yoksa ekle, varsa id'sini al)
        BEGIN
            SELECT id INTO v_author_id FROM AUTHORS WHERE name = p_author_name;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO AUTHORS (name) VALUES (p_author_name) RETURNING id INTO v_author_id;
        END;

        -- Yayınevi kontrolü (Yoksa ekle, varsa id'sini al)
        BEGIN
            SELECT id INTO v_publisher_id FROM PUBLISHERS WHERE name = p_publisher_name;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO PUBLISHERS (name) VALUES (p_publisher_name) RETURNING id INTO v_publisher_id;
        END;

        -- Kitap kaydını oluştur
        INSERT INTO BOOKS (title, author_id, publisher_id)
        VALUES (p_title, v_author_id, v_publisher_id);
        
        COMMIT;
    END add_book;
END BOOK_OPERATIONS;
/